// Code generated by options-gen. DO NOT EDIT.
package {{ .packageName }}

import (
    "github.com/pkg/errors"
    "golang.org/x/sync/errgroup"
	"github.com/kazhuravlev/options-gen/validator"
	{{- range $import := .imports }}
	{{ $import -}}
	{{- end }}
)

type opt{{ .optionsStructName }}Meta struct {
	setter    func(o *{{ .optionsStructName }})
	validator func(o *{{ .optionsStructName }}) error
}

{{ range .options }}
	func _{{ $.optionsStructName }}_{{ .Field }}Validator(o *{{ $.optionsStructName }}) error {
		{{ if .TagOption.IsNotEmpty -}}
			if validator.IsNil(o.{{ .Field }}) {
				return errors.Wrap(ErrInvalidOption, "{{ .Field }} must be set (type {{ .Type }})")
			}
		{{- end }}
		return nil
	}

	{{ if not .TagOption.IsRequired }}
		func With{{ .Name }}(opt {{ .Type }}) opt{{ $.optionsStructName }}Meta {
			 return opt{{ $.optionsStructName }}Meta{
				 setter: func(o *{{ $.optionsStructName }}) { o.{{ .Field }} = opt },
				 validator: _{{ $.optionsStructName }}_{{ .Field }}Validator,
			 }
		}
	{{ end }}
{{ end }}


func New{{ .optionsStructName }}(
	{{ range .options }}{{ if .TagOption.IsRequired -}}
		{{ .Field }} {{ .Type }},
	{{ end }}{{ end }}
	options ...opt{{ .optionsStructName }}Meta,
) {{ .optionsStructName }} {
	o := {{ .optionsStructName }}{}
	{{ range .options }}{{ if .TagOption.IsRequired -}}
		o.{{ .Field }} = {{ .Field }}
	{{ end }}{{ end }}

	for i := range options{
		options[i].setter(&o)
	}

	return o
}

func (o *{{ .optionsStructName }}) Validate() error {
    g := new(errgroup.Group)

	{{ range .options -}}
	    g.Go(func() error {
	        err := _{{ $.optionsStructName }}_{{ .Field }}Validator(o)

	        return errors.Wrap(err, "invalid value for option With{{ .Name }}")
	    })
	{{ end -}}

	return g.Wait()
}
