// Code generated by options-gen. DO NOT EDIT.
package {{ .packageName }}

import (
	"fmt"
	"github.com/kazhuravlev/options-gen/validator"
	{{- range $import := .imports }}
	{{ $import -}}
	{{- end }}
)

type opt{{ .optionsStructName }}Meta struct {
	setter    func(o *{{ .optionsStructName }})
	validator func(o *{{ .optionsStructName }}) error
}

{{ range .options }}
	func _{{ $.optionsStructName }}_{{ .Field }}Validator(o *{{ $.optionsStructName }}) error {
		{{ if .TagOption.IsNotEmpty -}}
			if validator.IsNil(o.{{ .Field }}) {
				return fmt.Errorf("%w: {{ .Field }} must be set (type {{ .Type }})", ErrInvalidOption)
			}
		{{- end }}
		return nil
	}

	{{ if not .TagOption.IsRequired }}
		func With{{ .Name }}(opt {{ .Type }}) opt{{ $.optionsStructName }}Meta {
			 return opt{{ $.optionsStructName }}Meta{
				 setter: func(o *{{ $.optionsStructName }}) { o.{{ .Field }} = opt },
				 validator: _{{ $.optionsStructName }}_{{ .Field }}Validator,
			 }
		}
	{{ end }}
{{ end }}


func New{{ .optionsStructName }}(
	{{ range .options }}{{ if .TagOption.IsRequired -}}
		{{ .Field }} {{ .Type }},
	{{ end }}{{ end }}
	options ...opt{{ .optionsStructName }}Meta,
) {{ .optionsStructName }} {
	o := {{ .optionsStructName }}{}
	{{ range .options }}{{ if .TagOption.IsRequired -}}
		o.{{ .Field }} = {{ .Field }}
	{{ end }}{{ end }}

	for i := range options{
		options[i].setter(&o)
	}

	return o
}

func (o *{{ .optionsStructName }}) Validate() error {
	{{ range .options -}}
		if err := _{{ $.optionsStructName }}_{{ .Field }}Validator(o); err != nil{
			return fmt.Errorf("%w: invalid value for option With{{ .Name }}", err)
		}

	{{ end -}}

	return nil
}
