// Code generated by options-gen qa-version. DO NOT EDIT.

package testcase

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type optField int8

const (
	FieldvalInt        optField = 0
	FieldvalInt8       optField = 1
	FieldvalInt16      optField = 2
	FieldvalInt32      optField = 3
	FieldvalInt64      optField = 4
	FieldvalUInt       optField = 5
	FieldvalUInt8      optField = 6
	FieldvalUInt16     optField = 7
	FieldvalUInt32     optField = 8
	FieldvalUInt64     optField = 9
	FieldvalFloat32    optField = 10
	FieldvalFloat64    optField = 11
	FieldvalString     optField = 12
	FieldvalBytes      optField = 13
	FieldvalBool       optField = 14
	FieldoptValInt     optField = 15
	FieldoptValInt8    optField = 16
	FieldoptValInt16   optField = 17
	FieldoptValInt32   optField = 18
	FieldoptValInt64   optField = 19
	FieldoptValUInt    optField = 20
	FieldoptValUInt8   optField = 21
	FieldoptValUInt16  optField = 22
	FieldoptValUInt32  optField = 23
	FieldoptValUInt64  optField = 24
	FieldoptValFloat32 optField = 25
	FieldoptValFloat64 optField = 26
	FieldoptValString  optField = 27
	FieldoptValBytes   optField = 28
	FieldoptValBool    optField = 29
)

var optIsSet = [30]bool{}

type OptOptionsSetter func(o *Options)

func NewOptions(
	valInt int,
	valInt8 int8,
	valInt16 int16,
	valInt32 int32,
	valInt64 int64,
	valUInt uint,
	valUInt8 uint8,
	valUInt16 uint16,
	valUInt32 uint32,
	valUInt64 uint64,
	valFloat32 float32,
	valFloat64 float64,
	valString string,
	valBytes []byte,
	valBool bool,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	var empty [30]bool
	optIsSet = empty

	// Setting defaults from field tag (if present)

	o.valInt = valInt
	optIsSet[FieldvalInt] = true
	o.valInt8 = valInt8
	optIsSet[FieldvalInt8] = true
	o.valInt16 = valInt16
	optIsSet[FieldvalInt16] = true
	o.valInt32 = valInt32
	optIsSet[FieldvalInt32] = true
	o.valInt64 = valInt64
	optIsSet[FieldvalInt64] = true
	o.valUInt = valUInt
	optIsSet[FieldvalUInt] = true
	o.valUInt8 = valUInt8
	optIsSet[FieldvalUInt8] = true
	o.valUInt16 = valUInt16
	optIsSet[FieldvalUInt16] = true
	o.valUInt32 = valUInt32
	optIsSet[FieldvalUInt32] = true
	o.valUInt64 = valUInt64
	optIsSet[FieldvalUInt64] = true
	o.valFloat32 = valFloat32
	optIsSet[FieldvalFloat32] = true
	o.valFloat64 = valFloat64
	optIsSet[FieldvalFloat64] = true
	o.valString = valString
	optIsSet[FieldvalString] = true
	o.valBytes = valBytes
	optIsSet[FieldvalBytes] = true
	o.valBool = valBool
	optIsSet[FieldvalBool] = true

	for _, opt := range options {
		opt(&o)
	}
	return o
}

// optValInt docstring-1
func WithOptValInt(opt int) OptOptionsSetter {
	return func(o *Options) {
		o.optValInt = opt
		optIsSet[FieldoptValInt] = true
	}
}

// docstring-2
func WithOptValInt8(opt int8) OptOptionsSetter {
	return func(o *Options) {
		o.optValInt8 = opt
		optIsSet[FieldoptValInt8] = true
	}
}

func WithOptValInt16(opt int16) OptOptionsSetter {
	return func(o *Options) {
		o.optValInt16 = opt
		optIsSet[FieldoptValInt16] = true
	}
}

// Just
// a
// comment
func WithOptValInt32(opt int32) OptOptionsSetter {
	return func(o *Options) {
		o.optValInt32 = opt
		optIsSet[FieldoptValInt32] = true
	}
}

// Just
// a
// comment
func WithOptValInt64(opt int64) OptOptionsSetter {
	return func(o *Options) {
		o.optValInt64 = opt
		optIsSet[FieldoptValInt64] = true
	}
}

func WithOptValUInt(opt uint) OptOptionsSetter {
	return func(o *Options) {
		o.optValUInt = opt
		optIsSet[FieldoptValUInt] = true
	}
}

func WithOptValUInt8(opt uint8) OptOptionsSetter {
	return func(o *Options) {
		o.optValUInt8 = opt
		optIsSet[FieldoptValUInt8] = true
	}
}

func WithOptValUInt16(opt uint16) OptOptionsSetter {
	return func(o *Options) {
		o.optValUInt16 = opt
		optIsSet[FieldoptValUInt16] = true
	}
}

func WithOptValUInt32(opt uint32) OptOptionsSetter {
	return func(o *Options) {
		o.optValUInt32 = opt
		optIsSet[FieldoptValUInt32] = true
	}
}

func WithOptValUInt64(opt uint64) OptOptionsSetter {
	return func(o *Options) {
		o.optValUInt64 = opt
		optIsSet[FieldoptValUInt64] = true
	}
}

func WithOptValFloat32(opt float32) OptOptionsSetter {
	return func(o *Options) {
		o.optValFloat32 = opt
		optIsSet[FieldoptValFloat32] = true
	}
}

func WithOptValFloat64(opt float64) OptOptionsSetter {
	return func(o *Options) {
		o.optValFloat64 = opt
		optIsSet[FieldoptValFloat64] = true
	}
}

func WithOptValString(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.optValString = opt
		optIsSet[FieldoptValString] = true
	}
}

func WithOptValBytes(opt ...byte) OptOptionsSetter {
	return func(o *Options) {
		o.optValBytes = append(o.optValBytes, opt...)
		optIsSet[FieldoptValBytes] = true
	}
}

func WithOptValBool(opt bool) OptOptionsSetter {
	return func(o *Options) {
		o.optValBool = opt
		optIsSet[FieldoptValBool] = true
	}
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("optValInt", _validate_Options_optValInt(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValInt8", _validate_Options_optValInt8(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValInt16", _validate_Options_optValInt16(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValInt32", _validate_Options_optValInt32(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValInt64", _validate_Options_optValInt64(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValUInt", _validate_Options_optValUInt(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValUInt8", _validate_Options_optValUInt8(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValUInt16", _validate_Options_optValUInt16(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValUInt32", _validate_Options_optValUInt32(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValUInt64", _validate_Options_optValUInt64(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValFloat32", _validate_Options_optValFloat32(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValFloat64", _validate_Options_optValFloat64(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValString", _validate_Options_optValString(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValBytes", _validate_Options_optValBytes(o)))
	errs.Add(errors461e464ebed9.NewValidationError("optValBool", _validate_Options_optValBool(o)))
	return errs.AsError()
}

func (o *Options) IsSet(field optField) bool {
	return optIsSet[field]
}

func _validate_Options_optValInt(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValInt, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValInt` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValInt8(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValInt8, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValInt8` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValInt16(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValInt16, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValInt16` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValInt32(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValInt32, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValInt32` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValInt64(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValInt64, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValInt64` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValUInt(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValUInt, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValUInt` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValUInt8(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValUInt8, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValUInt8` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValUInt16(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValUInt16, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValUInt16` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValUInt32(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValUInt32, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValUInt32` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValUInt64(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValUInt64, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValUInt64` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValFloat32(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValFloat32, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValFloat32` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValFloat64(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValFloat64, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValFloat64` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValString(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValString, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValString` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValBytes(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValBytes, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValBytes` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_optValBool(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.optValBool, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `optValBool` did not pass the test: %w", err)
	}
	return nil
}
