// Code generated by options-gen qa-version. DO NOT EDIT.

package testcase

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithName(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.name = opt
	}
}

func (o *Options) Validate() error {
	return nil
}
