run:
  tests: true

issues:
  max-same-issues: 0

linters-settings:
  lll:
    line-length: 120
  depguard:
    rules:
      main:
        # List of file globs that will match this list of settings to compare against.
        # Default: $all
        files:
          - "$all"
        # List of allowed packages.
        allow: [ ]
        # Packages that are not allowed where the value is a suggestion.
        deny:
          - pkg: "github.com/pkg/errors"
            desc: Use a standard library
  varnamelen:
    ignore-names:
      - err
      - i

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - unused
    - depguard
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - exhaustruct
    - forbidigo
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - nilnil
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nestif
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - varnamelen
    - staticcheck
    - nlreturn
    - mnd
    - exhaustruct
