version: '3'

silent: true

tasks:
  default:
    cmds:
      - task --list-all

  check:
    desc: Run all project checks
    cmds:
      - echo "- Run all routines"
      - task: tidy
      - task: tools:install
      - task: fmt
      - task: lint
      - task: install
      - task: tests
      - task: examples:update

  tidy:
    cmds:
      - echo "- Tidy"
      - go mod tidy

  fmt:
    desc: Run code formatter
    cmds:
      - echo "- Format"
      - go fmt ./...

  tools:install:
    desc: Install required tools (into local project dir)
    run: once
    cmds:
      - echo "- Run install tools"
      - go run github.com/kazhuravlev/toolset/cmd/toolset@latest sync

  lint:
    desc: Run linter
    cmds:
      - echo "- Lint"
      - task: 'tools:install'
      - toolset run golangci-lint run --fix ./...

  install:
    run: once
    cmds:
      - echo "- Install"
      - go install ./cmd/options-gen

  tests:
    cmds:
      - echo "- Tests"
      - go test -race -count 1 ./...

  examples:update:
    desc: Update examples directory
    cmds:
      - echo "- Update examples"
      - task: examples:update:go-generate
      - task: examples:update:go-generate-generics
      - task: examples:update:go-generate-2options-1pkg
      - task: examples:update:library

  examples:update:library:
    dir: examples/library
    cmds:
      - go run main.go
      - go test .

  examples:update:go-generate:
    dir: examples/go-generate
    cmds:
      - task: "install"
      - go generate ./...

  examples:update:go-generate-generics:
    dir: examples/go-generate-generics
    cmds:
      - task: "install"
      - go generate ./...

  examples:update:go-generate-2options-1pkg:
    dir: examples/go-generate-2options-1pkg
    cmds:
      - task: "install"
      - go generate ./...
