// Code generated by options-gen. DO NOT EDIT.
package {{ .packageName }}

import (
    "fmt"
    uniqprefixformultierror "github.com/hashicorp/go-multierror"
	"github.com/kazhuravlev/options-gen/pkg/validator"
	goplvalidator "github.com/go-playground/validator/v10"
	{{- range $import := .imports }}
	{{ $import -}}
	{{- end }}
)
{{ if .hasValidation }}
var _validator461e464ebed9 = goplvalidator.New()
{{- end }}

type opt{{ .optionsStructName }}Meta struct {
	setter    func(o *{{ .optionsStructName }})
	validator func(o *{{ .optionsStructName }}) error
}

func New{{ .optionsStructName }}(
	{{ range .options -}}
        {{ if .TagOption.IsRequired -}}
            {{ .Field }} {{ .Type }},
        {{ end }}
	{{- end }}
	options ...opt{{ .optionsStructName }}Meta,
) {{ .optionsStructName }} {
	o := {{ .optionsStructName }}{}
	{{ range .options }}{{ if .TagOption.IsRequired -}}
		o.{{ .Field }} = {{ .Field }}
	{{ end }}{{ end }}

	for i := range options{
		options[i].setter(&o)
	}

	return o
}

{{ range .options }}
	{{ if not .TagOption.IsRequired }}
		func With{{ .Name }}(opt {{ .Type }}) opt{{ $.optionsStructName }}Meta {
			 return opt{{ $.optionsStructName }}Meta{
				 setter: func(o *{{ $.optionsStructName }}) { o.{{ .Field }} = opt },
				 validator: _{{ $.optionsStructName }}_{{ .Field }}Validator,
			 }
		}
	{{ end }}
{{ end }}


func (o *{{ .optionsStructName }}) Validate() error {
    var g uniqprefixformultierror.Group

	{{ range .options -}}
	    g.Go(func() error {
	        err := _{{ $.optionsStructName }}_{{ .Field }}Validator(o)
	        if err != nil {
	            return fmt.Errorf("invalid value for option With{{ .Name }}: %w", err)
	        }
	        return nil
	    })
	{{ end -}}

	return g.Wait().ErrorOrNil()
}

{{ range .options }}
	func _{{ $.optionsStructName }}_{{ .Field }}Validator(o *{{ $.optionsStructName }}) error {
		{{ if .TagOption.IsNotEmpty -}}
			if validator.IsNil(o.{{ .Field }}) {
				return fmt.Errorf("%w: {{ .Field }} must be present (type {{ .Type }})", ErrInvalidOption)
			}
		{{- end }}

		{{ if .TagOption.GoValidator -}}
            if err := _validator461e464ebed9.Var(o.{{ .Field }}, "{{ .TagOption.GoValidator }}"); err != nil {
                return fmt.Errorf("field `{{ .Field }}` did not pass the test: %w", err)
            }
		{{- end }}

		return nil
	}
{{ end }}
