// Code generated by options-gen. DO NOT EDIT.
package {{ .packageName }}

import (
	fmt461e464ebed9 "fmt"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
{{ if .hasValidation }}validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"{{ end }}
	{{- range $import := .imports }}
	{{ $import -}}
	{{- end }}
)

type Opt{{ $.optionsStructName }}Setter{{ $.optionsTypeParamsSpec }} func(o *{{ .optionsStructInstanceType }})

func New{{ .optionsStructType }}(
	{{ range .options -}}
		{{ if .TagOption.IsRequired -}}
			{{ .Field }} {{ .Type }},
		{{ end }}
	{{- end -}}
	options ...Opt{{ $.optionsStructName }}Setter{{ $.optionsTypeParams }},
) {{ .optionsStructInstanceType }} {
	o := {{ .optionsStructInstanceType }}{}
	{{ range .options }}
	    {{- if .TagOption.IsRequired -}}
	        o.{{ .Field }} = {{ .Field }}
        {{ end -}}
	    {{ if .TagOption.Default -}}
            {{ if eq .Type "time.Duration" }}o.{{ .Field }}, _ = time.ParseDuration("{{ .TagOption.Default }}")
            {{- else if eq .Type "string" }}o.{{ .Field }} = "{{ .TagOption.Default }}"
            {{- else }}o.{{ .Field }} = {{ .TagOption.Default }}{{ end }}
	    {{ end -}}
	{{ end }}

	for _, opt := range options {
		opt(&o)
	}
	return o
}

{{ range .options }}
	{{ if not .TagOption.IsRequired }}
		func With{{ .Name }}{{ $.optionsTypeParamsSpec }}(opt {{ .Type }}) Opt{{ $.optionsStructName }}Setter{{ $.optionsTypeParams }} {
			return func(o *{{ $.optionsStructInstanceType }}) {
				o.{{ .Field }} = opt
			}
		}
	{{ end }}
{{ end }}

func (o *{{ .optionsStructInstanceType }}) Validate() error {
	{{- if not .hasValidation -}}
		return nil
	{{- else }}
		errs := new(errors461e464ebed9.ValidationErrors)
		{{- range .options }}
			{{- if .TagOption.GoValidator }}
				errs.Add(errors461e464ebed9.NewValidationError("{{ .Field }}", _validate_{{ $.optionsStructName }}_{{ .Field }}{{ $.optionsTypeParams }}(o)))
			{{- end }}
		{{- end }}
		return errs.AsError()
	{{- end }}
}

{{ range .options }}
	{{- if .TagOption.GoValidator }}
		func _validate_{{ $.optionsStructName }}_{{ .Field }}{{ $.optionsTypeParamsSpec }}(o *{{ $.optionsStructInstanceType }}) error {
			if err := validator461e464ebed9.GetValidatorFor(o).Var(o.{{ .Field }}, "{{ .TagOption.GoValidator }}"); err != nil {
				return fmt461e464ebed9.Errorf("field `{{ .Field }}` did not pass the test: %w", err)
			}
			return nil
		}
	{{- end }}
{{ end }}
