// Code generated by options-gen. DO NOT EDIT.
package testcase

import (
	"fmt"
	"io"
)

type optionsSetter func(o *Options)

func NewOptions(
	Any any,
	Stringer fmt.Stringer,
	RWCloser io.ReadWriteCloser,
	Local localInterface,
	options ...optionsSetter,
) Options {
	o := Options{}
	o.Any = Any
	o.Stringer = Stringer
	o.RWCloser = RWCloser
	o.Local = Local

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithOptAny(opt any) optionsSetter {
	return func(o *Options) {
		o.OptAny = opt
	}
}

func WithOptStringer(opt fmt.Stringer) optionsSetter {
	return func(o *Options) {
		o.OptStringer = opt
	}
}

func WithOptRWCloser(opt io.ReadWriteCloser) optionsSetter {
	return func(o *Options) {
		o.OptRWCloser = opt
	}
}

func WithOptLocal(opt localInterface) optionsSetter {
	return func(o *Options) {
		o.OptLocal = opt
	}
}

func (o *Options) Validate() error {
	return nil
}
