// Code generated by options-gen qa-version. DO NOT EDIT.

package gogenerate

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type optKKKField int8

const (
	FieldKKKfield0 optKKKField = 0
	FieldKKKfield1 optKKKField = 1
	FieldKKKfield2 optKKKField = 2
	FieldKKKfield3 optKKKField = 3
)

var optKKKIsSet = [4]bool{}

type OptOptions1Setter func(o *Options1)

func NewOptions1(
	options ...OptOptions1Setter,
) Options1 {
	var o Options1

	var empty [4]bool
	optKKKIsSet = empty

	// Setting defaults from variable
	o.field0 = defaultOptions1.field0
	optKKKIsSet[FieldKKKfield0] = true
	o.field1 = defaultOptions1.field1
	optKKKIsSet[FieldKKKfield1] = true
	o.field2 = defaultOptions1.field2
	optKKKIsSet[FieldKKKfield2] = true
	o.field3 = defaultOptions1.field3
	optKKKIsSet[FieldKKKfield3] = true

	for _, opt := range options {
		opt(&o)
	}
	return o
}

// Options1.field0
func WithKKKField0(opt int) OptOptions1Setter {
	return func(o *Options1) {
		o.field0 = opt
		optKKKIsSet[FieldKKKfield0] = true
	}
}

// Options1.field1
func WithKKKField1(opt int) OptOptions1Setter {
	return func(o *Options1) {
		o.field1 = opt
		optKKKIsSet[FieldKKKfield1] = true
	}
}

// Options1.field2
func WithKKKField2(opt int) OptOptions1Setter {
	return func(o *Options1) {
		o.field2 = opt
		optKKKIsSet[FieldKKKfield2] = true
	}
}

// Options1.field3
func WithKKKField3(opt int) OptOptions1Setter {
	return func(o *Options1) {
		o.field3 = opt
		optKKKIsSet[FieldKKKfield3] = true
	}
}

func (o *Options1) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("field0", _validate_Options1_field0(o)))
	errs.Add(errors461e464ebed9.NewValidationError("field1", _validate_Options1_field1(o)))
	errs.Add(errors461e464ebed9.NewValidationError("field2", _validate_Options1_field2(o)))
	errs.Add(errors461e464ebed9.NewValidationError("field3", _validate_Options1_field3(o)))
	return errs.AsError()
}

func (o *Options1) IsSet(field optKKKField) bool {
	return optKKKIsSet[field]
}

func _validate_Options1_field0(o *Options1) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.field0, "min:3"); err != nil {
		return fmt461e464ebed9.Errorf("field `field0` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options1_field1(o *Options1) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.field1, "min:3"); err != nil {
		return fmt461e464ebed9.Errorf("field `field1` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options1_field2(o *Options1) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.field2, "min:3"); err != nil {
		return fmt461e464ebed9.Errorf("field `field2` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options1_field3(o *Options1) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.field3, "min:3"); err != nil {
		return fmt461e464ebed9.Errorf("field `field3` did not pass the test: %w", err)
	}
	return nil
}
