// Code generated by options-gen. DO NOT EDIT.
package testcase

import (
	"fmt"

	goplvalidator "github.com/go-playground/validator/v10"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
)

var _validator461e464ebed9 = goplvalidator.New()

type OptOptionsSetter func(o *Options)

func NewOptions(
	amount int,
	age int,
	options ...OptOptionsSetter,
) Options {
	o := Options{}
	o.amount = amount
	o.age = age

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("Age", _validate_Options_age(o)))
	return errs.AsError()
}

func _validate_Options_age(o *Options) error {
	if err := _getOptsValidatorOrDefault(o).Var(o.age, "adult"); err != nil {
		return fmt.Errorf("field `age` did not pass the test: %w", err)
	}
	return nil
}

func _getOptsValidatorOrDefault(opts any) *goplvalidator.Validate {
	if v, ok := opts.(interface {
		Validator() *goplvalidator.Validate
	}); ok {
		return v.Validator()
	}
	return _validator461e464ebed9
}
