// Code generated by options-gen. DO NOT EDIT.
package cli

import (
	"fmt"
	"net/http"

	goplvalidator "github.com/go-playground/validator/v10"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
)

var _validator461e464ebed9 = goplvalidator.New()

type optionsSetter func(o *Options)

func NewOptions(
	httpClient *http.Client,
	token string,
	options ...optionsSetter,
) Options {
	o := Options{}
	o.httpClient = httpClient
	o.token = token

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("HttpClient", _validate_Options_httpClient(o)))
	return errs.AsError()
}

func _validate_Options_httpClient(o *Options) error {
	if err := _validator461e464ebed9.Var(o.httpClient, "required"); err != nil {
		return fmt.Errorf("field `httpClient` did not pass the test: %w", err)
	}
	return nil
}
