// Code generated by options-gen. DO NOT EDIT.
package testcase

type optOptionsSetter func(o *Options)

func NewOptions(
	options ...optOptionsSetter,
) Options {
	o := Options{}

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	return nil
}
