// Code generated by options-gen. DO NOT EDIT.
package testcase

import (
	uniqprefixformultierror "github.com/hashicorp/go-multierror"
)

type optOptionsMeta struct {
	setter    func(o *Options)
	validator func(o *Options) error
}

func NewOptions(

	options ...optOptionsMeta,
) Options {
	o := Options{}

	for i := range options {
		options[i].setter(&o)
	}

	return o
}

func (o *Options) Validate() error {
	var g uniqprefixformultierror.Group

	return g.Wait().ErrorOrNil()
}
