// Code generated by options-gen qa-version. DO NOT EDIT.

package testcase

type OptOptionsSetter func(o *Options)

func WithName(opt string) OptOptionsSetter {
	return func(o *Options) { o.name = opt }
}

func (o *Options) Validate() error {
	return nil
}
