// Code generated by options-gen qa-version. DO NOT EDIT.

package gogenerate

type OptOptionsSetter[K comparable, V any] func(o *Options[K, V])

func NewOptions[K comparable, V any](
	options ...OptOptionsSetter[K, V],
) Options[K, V] {
	var o Options[K, V]

	// Setting defaults from func
	defaultOpts := getDefaultOptions[K, V]()
	o.defaultVal = defaultOpts.defaultVal

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithDefaultVal[K comparable, V any](opt V) OptOptionsSetter[K, V] {
	return func(o *Options[K, V]) { o.defaultVal = opt }
}

func (o *Options[K, V]) Validate() error {
	return nil
}
