// Code generated by options-gen qa-version. DO NOT EDIT.

package testcase

type optField int8

const ()

var optIsSet = [0]bool{}

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	var o Options

	var empty [0]bool
	optIsSet = empty

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	return nil
}

func (o *Options) IsSet(field optField) bool {
	return optIsSet[field]
}
