// Code generated by options-gen qa-version. DO NOT EDIT.

package testcase

import (
	"github.com/kazhuravlev/options-gen/options-gen/testdata/case-18-embed-inline-no-panic/embedpkg"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithEmbedStruct(opt EmbedStruct) OptOptionsSetter {
	return func(o *Options) {
		o.EmbedStruct = opt
	}
}

func WithStruct(opt *embedpkg.Struct) OptOptionsSetter {
	return func(o *Options) {
		o.Struct = opt
	}
}

func WithInline(opt struct{ inlineField string }) OptOptionsSetter {
	return func(o *Options) {
		o.inline = opt
	}
}

func WithName(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.name = opt
	}
}

func (o *Options) Validate() error {
	return nil
}
