// Code generated by options-gen qa-version. DO NOT EDIT.

package testcase

type OptOptionsSetter func(o *Options)

func NewOptions(
	TLS bool,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.tls = TLS

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	return nil
}
