package main

import (
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kazhuravlev/options-gen/internal/ctype"
	optionsgen "github.com/kazhuravlev/options-gen/options-gen"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const (
	e2eVersion       = "qa-version"
	e2eHeader        = "// Code generated by options-gen " + e2eVersion + ". DO NOT EDIT.\n"
	e2eVersionLdflag = "-X github.com/kazhuravlev/options-gen/internal/version.version=" + e2eVersion
)

// caseParams mirrors options-gen/testdata/*/.params.json, see options-gen/cmd_test.go.
type caseParams struct {
	OutPrefix      string                           `json:"out_prefix"` //nolint:tagliatelle
	Defaults       optionsgen.Defaults              `json:"defaults"`
	Constructor    optionsgen.ConstructorTypeRender `json:"constructor"`
	WithIsset      bool                             `json:"with_isset"`       //nolint:tagliatelle
	AllVariadic    bool                             `json:"all_variadic"`     //nolint:tagliatelle
	OptionTypeName string                           `json:"option_type_name"` //nolint:tagliatelle
}

func readCaseParams(t *testing.T, filename string) caseParams {
	t.Helper()

	params := caseParams{
		OutPrefix: "",
		Defaults: optionsgen.Defaults{
			From:  optionsgen.DefaultsFromTag,
			Param: "",
		},
		Constructor:    optionsgen.ConstructorPublicRender,
		WithIsset:      false,
		AllVariadic:    false,
		OptionTypeName: "",
	}

	content, err := os.ReadFile(filename)
	if errors.Is(err, os.ErrNotExist) {
		return params
	}

	require.NoError(t, err)
	require.NoError(t, json.Unmarshal(content, &params))

	return params
}

// cliArgs maps the test case params to the CLI flags the same way options-gen/cmd_test.go maps them to options.
func cliArgs(inputFile, outputFile string, params caseParams) []string {
	defaultsFrom := string(params.Defaults.From)
	if params.Defaults.Param != "" {
		defaultsFrom += "=" + params.Defaults.Param
	}

	args := []string{
		"-filename=" + inputFile,
		"-out-filename=" + outputFile,
		"-pkg=testcase",
		"-from-struct=Options",
		"-out-prefix=" + params.OutPrefix,
		"-defaults-from=" + defaultsFrom,
		"-constructor=" + string(params.Constructor),
		"-out-setter-name=" + params.OptionTypeName,
	}

	if params.WithIsset {
		args = append(args, "-with-isset")
	}

	if params.AllVariadic {
		args = append(args, "-all-variadic")
	}

	return args
}

// buildCLI builds the options-gen binary with a fixed version and returns its path.
func buildCLI(t *testing.T) string {
	t.Helper()

	if testing.Short() {
		t.Skip("skipping the CLI end-to-end test in short mode")
	}

	goBin, err := exec.LookPath("go")
	if err != nil {
		t.Skipf("go is not on PATH: %v", err)
	}

	binary := filepath.Join(t.TempDir(), "options-gen")

	build := exec.CommandContext(t.Context(), goBin, "build", "-o", binary, "-ldflags", e2eVersionLdflag, ".")

	output, err := build.CombinedOutput()
	require.NoError(t, err, string(output))

	return binary
}

// runCLI runs the binary in dir with the given extra environment and returns its combined output.
func runCLI(t *testing.T, binary, dir string, env []string, args ...string) (string, error) {
	t.Helper()

	cmd := exec.CommandContext(t.Context(), binary, args...)
	cmd.Dir = dir
	// Do not inherit GOFILE/GOPACKAGE from a `go generate` that may be running the tests.
	cmd.Env = append(os.Environ(), "GOFILE=", "GOPACKAGE=")
	cmd.Env = append(cmd.Env, env...)

	output, err := cmd.CombinedOutput()

	return string(output), err
}

func requireExitCode(t *testing.T, err error, want int) {
	t.Helper()

	var exitErr *exec.ExitError
	require.ErrorAs(t, err, &exitErr)
	assert.Equal(t, want, exitErr.ExitCode())
}

func TestCLI_EndToEnd(t *testing.T) {
	t.Parallel()

	binary := buildCLI(t)

	t.Run("testdata cases", func(t *testing.T) {
		t.Parallel()

		// Cases that only import the standard library, so a copy outside the module can be generated.
		cases := []string{
			"case-01-empty-options",
			"case-02-builtin-types",
			"case-02.1-builtin-types-all-variadic",
			"case-02.2-builtin-types-custom-option-type-name",
			"case-12-defaults-tag-02",
			"case-13-defaults-var",
			"case-14-defaults-func",
			"case-15-private-constructor",
			"case-16-without-cosntructor",
			"case-17-skip",
			"case-20-isset",
			"case-21-mandatory-custom-name",
		}

		for _, caseName := range cases {
			t.Run(caseName, func(t *testing.T) {
				t.Parallel()

				params := readCaseParams(t, filepath.Join(testdataDir, caseName, ".params.json"))

				inputFile := copyCase(t, caseName)
				workDir := filepath.Dir(inputFile)
				outputFile := filepath.Join(workDir, "options_generated.go")

				output, err := runCLI(t, binary, workDir, nil, cliArgs(inputFile, outputFile, params)...)
				require.NoError(t, err, output)

				actual := readTestFile(t, outputFile)

				assert.True(t, strings.HasPrefix(actual, e2eHeader), "header: %q", strings.SplitN(actual, "\n", 2)[0])
				assert.Equal(t, expectedOutput(t, caseName), actual)
			})
		}
	})

	t.Run("GOFILE and GOPACKAGE are used like under go generate", func(t *testing.T) {
		t.Parallel()

		workDir := t.TempDir()
		source := "package generated\n\n//go:generate options-gen -from-struct=Options\n" +
			"type Options struct {\n\tname string\n}\n"
		require.NoError(t, os.WriteFile(filepath.Join(workDir, "options.go"), []byte(source), ctype.DefaultPermission))

		env := []string{"GOFILE=options.go", "GOPACKAGE=generated"}

		output, err := runCLI(t, binary, workDir, env, "-from-struct=Options")
		require.NoError(t, err, output)

		generated := readTestFile(t, filepath.Join(workDir, "options_generated.go"))
		assert.True(t, strings.HasPrefix(generated, e2eHeader))
		assert.Contains(t, generated, "package generated\n")
		assert.Contains(t, generated, "func WithName(opt string) OptOptionsSetter")
	})

	t.Run("struct not found exits with a non-zero code", func(t *testing.T) {
		t.Parallel()

		workDir := t.TempDir()
		require.NoError(t, os.WriteFile(filepath.Join(workDir, "options.go"),
			[]byte("package generated\n\ntype Other struct{}\n"), ctype.DefaultPermission))

		outputFile := filepath.Join(workDir, "options_generated.go")

		output, err := runCLI(t, binary, workDir, nil, requiredArgs("options.go", outputFile)...)
		requireExitCode(t, err, 1)
		assert.Contains(t, output, "cannot run options gen")
		assert.Contains(t, output, "cannot find target struct")
		assert.NoFileExists(t, outputFile)
	})

	t.Run("missing flags exit with a non-zero code and usage", func(t *testing.T) {
		t.Parallel()

		output, err := runCLI(t, binary, "", nil)
		requireExitCode(t, err, 1)
		assert.Contains(t, output, "Usage of options-gen:")
		assert.Contains(t, output, "missed required options")
	})

	t.Run("invalid exclude exits with a non-zero code", func(t *testing.T) {
		t.Parallel()

		output, err := runCLI(t, binary, "", nil, append(requiredArgs("options.go", "out.go"), "-exclude=[")...)
		requireExitCode(t, err, 1)
		assert.Contains(t, output, "parse excludes: compile pattern '['")
	})

	t.Run("help exits with a zero code", func(t *testing.T) {
		t.Parallel()

		output, err := runCLI(t, binary, "", nil, "-h")
		require.NoError(t, err, output)
		assert.Contains(t, output, "Usage of options-gen:")
	})
}
