package main

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"syscall"
	"testing"

	"github.com/kazhuravlev/options-gen/internal/ctype"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const testdataDir = "../../options-gen/testdata"

var generatedHeader = regexp.MustCompile(`^// Code generated by options-gen \S+\. DO NOT EDIT\.$`)

func noEnv(string) string { return "" }

func envFrom(values map[string]string) func(string) string {
	return func(key string) string { return values[key] }
}

// writeTestSource writes sourceCode into a fresh temp dir and returns the input and output file paths.
func writeTestSource(t *testing.T, sourceCode string) (inputFile, outputFile string) {
	t.Helper()

	tmpDir := t.TempDir()
	inputFile = filepath.Join(tmpDir, "options.go")
	outputFile = filepath.Join(tmpDir, "options_generated.go")

	require.NoError(t, os.WriteFile(inputFile, []byte(sourceCode), ctype.DefaultPermission))

	return inputFile, outputFile
}

func readTestFile(t *testing.T, filename string) string {
	t.Helper()

	content, err := os.ReadFile(filename)
	require.NoError(t, err)

	return string(content)
}

// copyCase copies the options.go of a testdata case into a fresh temp dir and returns the copy's path.
// The generator parses the whole input directory, and the options-gen package tests rewrite
// options_generated.go inside the testdata dirs concurrently, so the cases must not be read in place.
func copyCase(t *testing.T, caseName string) string {
	t.Helper()

	source := readTestFile(t, filepath.Join(testdataDir, caseName, "options.go"))
	inputFile := filepath.Join(t.TempDir(), "options.go")

	require.NoError(t, os.WriteFile(inputFile, []byte(source), ctype.DefaultPermission))

	return inputFile
}

func expectedOutput(t *testing.T, caseName string) string {
	t.Helper()

	return readTestFile(t, filepath.Join(testdataDir, caseName, "options_generated.go.expected"))
}

func requiredArgs(inputFile, outputFile string) []string {
	return []string{
		"-filename=" + inputFile,
		"-out-filename=" + outputFile,
		"-pkg=testcase",
		"-from-struct=Options",
	}
}

func TestRun_MissedRequiredOptions(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		args []string
	}{
		{name: "no args", args: nil},
		{name: "no from-struct", args: []string{"-filename=options.go", "-pkg=pkg", "-out-filename=out.go"}},
		{name: "no filename", args: []string{"-from-struct=Options", "-pkg=pkg", "-out-filename=out.go"}},
		{name: "no pkg", args: []string{"-filename=options.go", "-from-struct=Options", "-out-filename=out.go"}},
		{name: "no out-filename without GOFILE", args: []string{"-filename=options.go", "-pkg=pkg", "-from-struct=Options"}},
		{
			name: "empty defaults-from",
			args: []string{
				"-filename=options.go", "-pkg=pkg", "-from-struct=Options", "-out-filename=out.go", "-defaults-from=",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var out bytes.Buffer

			err := run(tt.args, noEnv, &out)
			require.ErrorIs(t, err, errMissedRequiredOptions)
			assert.Contains(t, out.String(), "Usage of options-gen:")
			assert.Contains(t, out.String(), "-from-struct")
		})
	}
}

func TestRun_EnvDefaults(t *testing.T) {
	t.Parallel()

	t.Run("GOFILE and GOPACKAGE fill filename and pkg", func(t *testing.T) {
		t.Parallel()

		inputFile, outputFile := writeTestSource(t, "package testcase\n\ntype Options struct {\n\tname string\n}\n")
		getenv := envFrom(map[string]string{"GOFILE": inputFile, "GOPACKAGE": "testcase"})

		var out bytes.Buffer

		err := run([]string{"-from-struct=Options", "-out-filename=" + outputFile}, getenv, &out)
		require.NoError(t, err, out.String())

		generated := readTestFile(t, outputFile)
		assert.Contains(t, generated, "package testcase\n")
		assert.Contains(t, generated, "func WithName(opt string) OptOptionsSetter")
	})

	t.Run("out-filename defaults to GOFILE with the _generated suffix", func(t *testing.T) {
		t.Parallel()

		getenv := envFrom(map[string]string{"GOFILE": "options.go", "GOPACKAGE": "testcase"})

		var out bytes.Buffer

		// Missing -from-struct triggers the usage, which shows the computed defaults.
		err := run(nil, getenv, &out)
		require.ErrorIs(t, err, errMissedRequiredOptions)
		assert.Contains(t, out.String(), `(default "options_generated.go")`)
		assert.Contains(t, out.String(), `(default "testcase")`)
	})

	t.Run("explicit flags win over the environment", func(t *testing.T) {
		t.Parallel()

		inputFile, outputFile := writeTestSource(t, "package other\n\ntype Options struct {\n\tname string\n}\n")
		getenv := envFrom(map[string]string{"GOFILE": "missing.go", "GOPACKAGE": "wrong"})

		var out bytes.Buffer

		err := run(append(requiredArgs(inputFile, outputFile), "-pkg=other"), getenv, &out)
		require.NoError(t, err, out.String())
		assert.Contains(t, readTestFile(t, outputFile), "package other\n")
	})
}

func TestRun_FlagParsing(t *testing.T) {
	t.Parallel()

	t.Run("help prints usage and succeeds", func(t *testing.T) {
		t.Parallel()

		var out bytes.Buffer

		require.NoError(t, run([]string{"-h"}, noEnv, &out))
		assert.Contains(t, out.String(), "Usage of options-gen:")
		assert.Contains(t, out.String(), "-defaults-from")
	})

	t.Run("unknown flag", func(t *testing.T) {
		t.Parallel()

		var out bytes.Buffer

		err := run([]string{"-bogus"}, noEnv, &out)
		require.ErrorContains(t, err, "parse flags: flag provided but not defined: -bogus")
		assert.Contains(t, out.String(), "Usage of options-gen:")
	})

	t.Run("invalid bool value", func(t *testing.T) {
		t.Parallel()

		var out bytes.Buffer

		err := run([]string{"-with-isset=maybe"}, noEnv, &out)
		require.ErrorContains(t, err, "parse flags")
		assert.Contains(t, err.Error(), "with-isset")
	})
}

func TestRun_BadDefaultsSpec(t *testing.T) {
	t.Parallel()

	t.Run("unknown source", func(t *testing.T) {
		t.Parallel()

		inputFile, outputFile := writeTestSource(t, "package testcase\n\ntype Options struct{}\n")

		var out bytes.Buffer

		err := run(append(requiredArgs(inputFile, outputFile), "-defaults-from=bogus=x"), noEnv, &out)
		require.EqualError(t, err, "bad defaults spec: bad syntax")
		assert.NoFileExists(t, outputFile)
	})

	t.Run("extra equals sign silently drops the parameter", func(t *testing.T) {
		t.Parallel()

		// Documented corner: "tag=a=b" is parsed as the tag source without a parameter, so the
		// `default` tag is used instead of `a`.
		inputFile, outputFile := writeTestSource(t,
			"package testcase\n\ntype Options struct {\n\tfield string `default:\"from-default\" a:\"from-a\"`\n}\n")

		var out bytes.Buffer

		err := run(append(requiredArgs(inputFile, outputFile), "-defaults-from=tag=a=b"), noEnv, &out)
		require.NoError(t, err, out.String())

		generated := readTestFile(t, outputFile)
		assert.Contains(t, generated, `o.field = "from-default"`)
		assert.NotContains(t, generated, "from-a")
	})
}

func TestRun_BadExclude(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		exclude string
		wantMsg string
	}{
		{name: "single invalid pattern", exclude: "[", wantMsg: "parse excludes: compile pattern '[': "},
		{name: "invalid pattern after a valid one", exclude: "^Ok;(", wantMsg: "compile pattern '(': "},
		{name: "trailing semicolon is an empty pattern that compiles", exclude: "^Ok;", wantMsg: ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			inputFile, outputFile := writeTestSource(t, "package testcase\n\ntype Options struct {\n\tfield string\n}\n")

			var out bytes.Buffer

			err := run(append(requiredArgs(inputFile, outputFile), "-exclude="+tt.exclude), noEnv, &out)
			if tt.wantMsg == "" {
				require.NoError(t, err, out.String())
				// The empty pattern matches every name, so every option is excluded.
				assert.NotContains(t, readTestFile(t, outputFile), "WithField(")

				return
			}

			require.ErrorContains(t, err, tt.wantMsg)
			assert.NoFileExists(t, outputFile)
		})
	}
}

func TestRun_GenerationFailure(t *testing.T) {
	t.Parallel()

	t.Run("struct not found", func(t *testing.T) {
		t.Parallel()

		inputFile, outputFile := writeTestSource(t, "package testcase\n\ntype Other struct{}\n")

		var out bytes.Buffer

		err := run(requiredArgs(inputFile, outputFile), noEnv, &out)
		require.ErrorContains(t, err, "cannot run options gen: cannot get options spec: cannot find target struct")
		assert.NoFileExists(t, outputFile)
	})

	t.Run("input file does not exist", func(t *testing.T) {
		t.Parallel()

		inputFile := filepath.Join(t.TempDir(), "missing.go")
		outputFile := filepath.Join(t.TempDir(), "options_generated.go")

		var out bytes.Buffer

		err := run(requiredArgs(inputFile, outputFile), noEnv, &out)
		require.ErrorContains(t, err, "cannot run options gen")
		assert.ErrorIs(t, err, syscall.ENOENT)
		assert.NoFileExists(t, outputFile)
	})

	t.Run("invalid out-setter-name", func(t *testing.T) {
		t.Parallel()

		inputFile, outputFile := writeTestSource(t, "package testcase\n\ntype Options struct{}\n")

		var out bytes.Buffer

		err := run(append(requiredArgs(inputFile, outputFile), "-out-setter-name=Opt2"), noEnv, &out)
		require.ErrorContains(t, err, "cannot run options gen")
		assert.ErrorContains(t, err, "must be a valid type name")
		assert.NoFileExists(t, outputFile)
	})
}

func TestRun_Success(t *testing.T) {
	t.Parallel()

	// The version of a test binary is not controlled by ldflags, so the header is compared by shape only.
	tests := []struct {
		caseDir string
		args    []string
	}{
		{caseDir: "case-01-empty-options", args: nil},
		{caseDir: "case-02.2-builtin-types-custom-option-type-name", args: []string{"-out-setter-name=CustomOpt"}},
		{caseDir: "case-12-defaults-tag-02", args: []string{"-out-prefix=Some", "-defaults-from=tag=my-default-tag"}},
		{caseDir: "case-13-defaults-var", args: []string{"-out-prefix=XXX", "-defaults-from=var=defaultOptions"}},
		{caseDir: "case-14-defaults-func", args: []string{"-out-prefix=Some", "-defaults-from=func=getDefaults"}},
		{caseDir: "case-15-private-constructor", args: []string{"-constructor=private"}},
		{caseDir: "case-16-without-cosntructor", args: []string{"-constructor=no"}},
		{caseDir: "case-19.2-all-variadic", args: []string{"-all-variadic", "-ignore-errors"}},
		{caseDir: "case-20-isset", args: []string{"-with-isset"}},
	}

	for _, tt := range tests {
		t.Run(tt.caseDir, func(t *testing.T) {
			t.Parallel()

			inputFile := copyCase(t, tt.caseDir)
			outputFile := filepath.Join(filepath.Dir(inputFile), "options_generated.go")

			var out bytes.Buffer

			err := run(append(requiredArgs(inputFile, outputFile), tt.args...), noEnv, &out)
			require.NoError(t, err, out.String())

			expected := expectedOutput(t, tt.caseDir)
			actual := readTestFile(t, outputFile)

			expectedHeader, expectedBody, _ := strings.Cut(expected, "\n")
			actualHeader, actualBody, _ := strings.Cut(actual, "\n")

			assert.Regexp(t, generatedHeader, expectedHeader)
			assert.Regexp(t, generatedHeader, actualHeader)
			assert.Equal(t, expectedBody, actualBody)
		})
	}
}

func TestRun_Warnings(t *testing.T) {
	t.Parallel()

	const publicFieldSource = "package testcase\n\ntype Options struct {\n\tPublicField string\n}\n"

	t.Run("warnings are written to the output", func(t *testing.T) {
		t.Parallel()

		inputFile, outputFile := writeTestSource(t, publicFieldSource)

		var out bytes.Buffer

		err := run(append(requiredArgs(inputFile, outputFile), "-ignore-errors"), noEnv, &out)
		require.NoError(t, err)
		assert.Contains(t, out.String(), "Warning: consider to make `PublicField` is private")
		assert.FileExists(t, outputFile)
	})

	t.Run("mute-warnings suppresses them", func(t *testing.T) {
		t.Parallel()

		inputFile, outputFile := writeTestSource(t, publicFieldSource)

		var out bytes.Buffer

		err := run(append(requiredArgs(inputFile, outputFile), "-mute-warnings", "-ignore-errors"), noEnv, &out)
		require.NoError(t, err)
		assert.Empty(t, out.String())
		assert.FileExists(t, outputFile)
	})
}

func TestRun_ExcludeFlag(t *testing.T) {
	t.Parallel()

	inputFile, outputFile := writeTestSource(t,
		"package testcase\n\ntype Options struct {\n\taddr string\n\tinternalConn string\n\tdebugMode bool\n}\n")

	var out bytes.Buffer

	err := run(append(requiredArgs(inputFile, outputFile), "-exclude=^Internal;^Debug"), noEnv, &out)
	require.NoError(t, err, out.String())

	generated := readTestFile(t, outputFile)
	assert.Contains(t, generated, "func WithAddr(opt string)")
	assert.NotContains(t, generated, "WithInternalConn(")
	assert.NotContains(t, generated, "WithDebugMode(")
}
