// Code generated by options-gen qa-version. DO NOT EDIT.

package testcase

import "net/http"

type OptOptionsSetter func(o *Options)

func NewOptions(
	F1 http.Client,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.F1 = F1

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	return nil
}
